### ISSUE TITLE
It's not working in Gitlab CI Server

### ISSUE THREAD

**Issue by wongjiahau** [facebook-atom/jest-electron-runner#47]
## Configurations
```js
// jest.config.js
module.exports = {
  "roots": [
    "./src"
  ],
  "transform": {
    "^.+\\.tsx?$": "ts-jest"
  },
  runner: '@jest-runner/electron',
  testEnvironment: '@jest-runner/electron/environment',
}
```

## Docker image
`nikolaik/python-nodejs:latest`

## What happened?
The log below is shown after running the `jest` command, and then it remained hanging and nothing happened after that, no output at all.
```
> jest --maxWorkers=1

(process:4814): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(electron:4814): Gtk-WARNING **: cannot open display: 
```

**Comment by boujeepossum** [comment]
hey @wongjiahau! running electron (or electron tests) require a display (or virtual display), and it seems like your CI server does  not support it, hence you get the message

> (electron:4814): Gtk-WARNING **: cannot open display: 

you can try using another docker image (see circleci configuration for this repo)
https://github.com/facebook-atom/jest-electron-runner/blob/master/.circleci/config.yml#L6

or you can play with things like `xvfb` to configure a virtual display

**Comment by agilgur5** [comment]
[Ran into a similar issue](https://github.com/agilgur5/physijs-webpack/pull/15#issuecomment-558864963) on Travis CI -- it would also hang, but it didn't print any errors while it waited, which was quite confusing.

For any future readers, I fixed it by following the links at https://github.com/d4rkr00t/jest-electron-runner/issues/5#issuecomment-489982074.

My Travis CI config looks a bit like this:

```yaml
language: node_js
node_js: '10.16.0'

# cache folder with Electron binary (https://github.com/electron/electron/blob/master/docs/tutorial/installation.md#cache)
cache:
  directories:
    - ~/.cache

# run with xvfb bc it's needed for Electron (https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-the-xvfb-run-wrapper)
script: xvfb-run npm test
```

The caching part isn't mentioned in the [Travis headless docs](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-the-xvfb-run-wrapper) or the [Electron headless CI docs](https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md), but it is mentioned in [Electron's installation docs](https://github.com/electron/electron/blob/master/docs/tutorial/installation.md#cache).

Hopefully this helps some folks! It might be worthwhile to officially document this for anyone who isn't knowledgeable about Electron + CI configuration. Can send a PR if this is agreed to be something that warrants officially documentation!
