### ISSUE TITLE
Fails to run on Gitlab CI

### ISSUE THREAD

**Issue by debjitbis08** [facebook-atom/jest-electron-runner#70]
### Configurations

`jest.config.js`
```javascript
module.exports = {
    setupFiles: ["./test-setup.js"],
    runner: "@jest-runner/electron",
    testEnvironment: "@jest-runner/electron/environment",
    collectCoverageFrom: ["**/*.js", "!**/node_modules/**"],
    coverageReporters: ["text", "lcov"],
    testResultsProcessor: "jest-sonar-reporter"
};
```

`.gitlab-ci.yml`
```yml
validation:
    stage: validation
    before_script:
        - apt-get update && apt-get install -y xvfb libxtst6 libnss3 libatk-bridge2.0-0 libgtk-3-0 libxss1 libasound2
    script:
        - npm ci --cache .npm --prefer-offline
        - echo "Running tests now"
        - export ELECTRON_DISABLE_SANDBOX=1
        - xvfb-run npm test
```

`package.json`
```json
  "scripts": {
    "test": "npm run lint && jest --config ./src/lib-code/jest.config.js",
    "lint": "eslint src/lib-code"
  },
  "devDependencies": {
    "electron": "^9.2.1",
    "jest": "^26.4.0"
  },
```

**Docker image used**: `node:latest`

### Output
```
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[1071:0819/190428.116634:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
```
To solve this I probably need to pass the `--disable-gpu` flag to electron, but I can't find a way to do it currently. Also, I have read [elsewhere](https://github.com/hustcc/jest-electron/issues/27#issuecomment-654949260) that running electron on Gitlab requires the `--disable-dev-shm-usage` flag but I don't think there is way to pass that parameter currently.
